// This file will be auto-generated by Supabase CLI
// Run: supabase gen types typescript --project-id YOUR_PROJECT_ID > src/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string | null
          avatar_url: string | null
          company: string | null
          job_title: string | null
          bio: string | null
          interests: string[] | null
          linkedin_url: string | null
          twitter_url: string | null
          website_url: string | null
          timezone: string
          language: string
          networking_enabled: boolean
          push_enabled: boolean
          reputation_score: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name?: string | null
          avatar_url?: string | null
          company?: string | null
          job_title?: string | null
          bio?: string | null
          interests?: string[] | null
          linkedin_url?: string | null
          twitter_url?: string | null
          website_url?: string | null
          timezone?: string
          language?: string
          networking_enabled?: boolean
          push_enabled?: boolean
          reputation_score?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string | null
          avatar_url?: string | null
          company?: string | null
          job_title?: string | null
          bio?: string | null
          interests?: string[] | null
          linkedin_url?: string | null
          twitter_url?: string | null
          website_url?: string | null
          timezone?: string
          language?: string
          networking_enabled?: boolean
          push_enabled?: boolean
          reputation_score?: number
          created_at?: string
          updated_at?: string
        }
      }
      conferences: {
        Row: {
          id: string
          slug: string
          name: string
          tagline: string | null
          description: string | null
          start_date: string
          end_date: string
          timezone: string
          venue_name: string | null
          venue_address: string | null
          venue_lat: number | null
          venue_lng: number | null
          logo_url: string | null
          banner_url: string | null
          primary_color: string
          secondary_color: string | null
          website_url: string | null
          is_public: boolean
          is_hybrid: boolean
          max_attendees: number | null
          registration_open: boolean
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          slug: string
          name: string
          tagline?: string | null
          description?: string | null
          start_date: string
          end_date: string
          timezone?: string
          venue_name?: string | null
          venue_address?: string | null
          venue_lat?: number | null
          venue_lng?: number | null
          logo_url?: string | null
          banner_url?: string | null
          primary_color?: string
          secondary_color?: string | null
          website_url?: string | null
          is_public?: boolean
          is_hybrid?: boolean
          max_attendees?: number | null
          registration_open?: boolean
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          slug?: string
          name?: string
          tagline?: string | null
          description?: string | null
          start_date?: string
          end_date?: string
          timezone?: string
          venue_name?: string | null
          venue_address?: string | null
          venue_lat?: number | null
          venue_lng?: number | null
          logo_url?: string | null
          banner_url?: string | null
          primary_color?: string
          secondary_color?: string | null
          website_url?: string | null
          is_public?: boolean
          is_hybrid?: boolean
          max_attendees?: number | null
          registration_open?: boolean
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      conference_members: {
        Row: {
          id: string
          conference_id: string
          user_id: string
          role: 'attendee' | 'speaker' | 'sponsor' | 'organizer' | 'staff'
          ticket_type: string | null
          ticket_code: string | null
          checked_in: boolean
          checked_in_at: string | null
          checked_in_by: string | null
          registered_at: string
        }
        Insert: {
          id?: string
          conference_id: string
          user_id: string
          role?: 'attendee' | 'speaker' | 'sponsor' | 'organizer' | 'staff'
          ticket_type?: string | null
          ticket_code?: string | null
          checked_in?: boolean
          checked_in_at?: string | null
          checked_in_by?: string | null
          registered_at?: string
        }
        Update: {
          id?: string
          conference_id?: string
          user_id?: string
          role?: 'attendee' | 'speaker' | 'sponsor' | 'organizer' | 'staff'
          ticket_type?: string | null
          ticket_code?: string | null
          checked_in?: boolean
          checked_in_at?: string | null
          checked_in_by?: string | null
          registered_at?: string
        }
      }
      sessions: {
        Row: {
          id: string
          conference_id: string
          track_id: string | null
          room_id: string | null
          title: string
          description: string | null
          session_type: 'keynote' | 'talk' | 'panel' | 'workshop' | 'networking' | 'break' | 'other'
          start_time: string
          end_time: string
          max_attendees: number | null
          requires_registration: boolean
          livestream_url: string | null
          replay_url: string | null
          slides_url: string | null
          transcript: string | null
          summary: string | null
          is_featured: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          conference_id: string
          track_id?: string | null
          room_id?: string | null
          title: string
          description?: string | null
          session_type?: 'keynote' | 'talk' | 'panel' | 'workshop' | 'networking' | 'break' | 'other'
          start_time: string
          end_time: string
          max_attendees?: number | null
          requires_registration?: boolean
          livestream_url?: string | null
          replay_url?: string | null
          slides_url?: string | null
          transcript?: string | null
          summary?: string | null
          is_featured?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          conference_id?: string
          track_id?: string | null
          room_id?: string | null
          title?: string
          description?: string | null
          session_type?: 'keynote' | 'talk' | 'panel' | 'workshop' | 'networking' | 'break' | 'other'
          start_time?: string
          end_time?: string
          max_attendees?: number | null
          requires_registration?: boolean
          livestream_url?: string | null
          replay_url?: string | null
          slides_url?: string | null
          transcript?: string | null
          summary?: string | null
          is_featured?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      tracks: {
        Row: {
          id: string
          conference_id: string
          name: string
          color: string | null
          description: string | null
          sort_order: number
        }
        Insert: {
          id?: string
          conference_id: string
          name: string
          color?: string | null
          description?: string | null
          sort_order?: number
        }
        Update: {
          id?: string
          conference_id?: string
          name?: string
          color?: string | null
          description?: string | null
          sort_order?: number
        }
      }
      rooms: {
        Row: {
          id: string
          conference_id: string
          name: string
          description: string | null
          capacity: number | null
          floor: string | null
          building: string | null
          map_x: number | null
          map_y: number | null
          has_livestream: boolean
          sort_order: number
        }
        Insert: {
          id?: string
          conference_id: string
          name: string
          description?: string | null
          capacity?: number | null
          floor?: string | null
          building?: string | null
          map_x?: number | null
          map_y?: number | null
          has_livestream?: boolean
          sort_order?: number
        }
        Update: {
          id?: string
          conference_id?: string
          name?: string
          description?: string | null
          capacity?: number | null
          floor?: string | null
          building?: string | null
          map_x?: number | null
          map_y?: number | null
          has_livestream?: boolean
          sort_order?: number
        }
      }
      saved_sessions: {
        Row: {
          id: string
          user_id: string
          session_id: string
          notes: string | null
          reminder_sent: boolean
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          session_id: string
          notes?: string | null
          reminder_sent?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          session_id?: string
          notes?: string | null
          reminder_sent?: boolean
          created_at?: string
        }
      }
      connections: {
        Row: {
          id: string
          requester_id: string
          recipient_id: string
          status: 'pending' | 'accepted' | 'declined'
          met_at_conference_id: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          requester_id: string
          recipient_id: string
          status?: 'pending' | 'accepted' | 'declined'
          met_at_conference_id?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          requester_id?: string
          recipient_id?: string
          status?: 'pending' | 'accepted' | 'declined'
          met_at_conference_id?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      messages: {
        Row: {
          id: string
          room_id: string
          sender_id: string
          content: string
          message_type: string
          metadata: Json | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          room_id: string
          sender_id: string
          content: string
          message_type?: string
          metadata?: Json | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          room_id?: string
          sender_id?: string
          content?: string
          message_type?: string
          metadata?: Json | null
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
